name: Update Arch Mirror Database and Files

on:
  push:
    branches:
      - main
    paths:
      - 'docs/linux/**/*'

jobs:
  update-db-and-files:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Arch Linux Tools inside Docker
        run: |
          # Use Docker to run Arch Linux tools inside a container
          docker run --rm -v $(pwd):/workspace archlinux:latest /bin/bash -c "
            pacman -Sy --noconfirm archlinux-keyring
            pacman -Sy --noconfirm repo-add
            # Now run your repo-add commands
            for folder in /workspace/docs/linux/*/; do
              db_file=\$folder/*.db.tar.gz
              files_file=\$folder/*.files.tar.gz
              if [[ -f \$db_file && -f \$files_file ]]; then
                repo-add \"\$folder/\$(basename \$folder).db\" \$db_file
                mv \$db_file \"\$folder/\$(basename \$folder).db.tar.gz\"
                mv \$files_file \"\$folder/\$(basename \$folder).files.tar.gz\"
                echo \"Created .db and .files for \$folder\"
              fi
            done
          "
          
      - name: Commit and push changes if any
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/linux/*
          git commit -m "Update .db and .files for new .tar.gz files"
          git push origin main
